name: Deploy React Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy automático no primeiro commit
  # Descomente as linhas abaixo se quiser deploy automático em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: ./frontend
        env:
          VITE_API_URL: https://app-expandev01-api-dev.azurewebsites.net
          VITE_API_BASE_URL: https://app-expandev01-api-dev.azurewebsites.net
          REACT_APP_API_URL: https://app-expandev01-api-dev.azurewebsites.net
          API_BASE_URL: https://app-expandev01-api-dev.azurewebsites.net
        run: |
          npm install
          echo "Building with API URL: https://app-expandev01-api-dev.azurewebsites.net"
          npm run build
          npm run test --if-present -- --passWithNoTests || true

      - name: Prepare for deployment
        working-directory: ./frontend
        run: |
          # Detectar pasta de build (Vite usa dist/, CRA usa build/)
          if [ -d "dist" ]; then
            BUILD_DIR="dist"
            echo "Using Vite output directory: dist/"
          elif [ -d "build" ]; then
            BUILD_DIR="build"
            echo "Using CRA output directory: build/"
          else
            echo "ERROR: No build output found (tried dist/ and build/)"
            exit 1
          fi

          # Verificar se o package.json já tem script start
          if grep -q '"start"' package.json; then
            echo "Start script already exists in package.json"
          else
            echo "No start script found. Adding serve for static hosting..."
            # Adicionar script start e dependência serve ao package.json existente
            npm install serve --save
            # Usar jq ou sed para adicionar o script start
            if [ "$BUILD_DIR" == "dist" ]; then
              # Para Vite (pasta dist)
              node -e "const pkg=require('./package.json'); pkg.scripts.start='npx serve -s dist -l 8080'; require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));"
            else
              # Para CRA (pasta build)
              node -e "const pkg=require('./package.json'); pkg.scripts.start='npx serve -s build -l 8080'; require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));"
            fi
            echo "Added start script to package.json"
          fi

      - name: Zip artifact for deployment
        working-directory: ./frontend
        run: |
          # Incluir tudo necessário para rodar a aplicação
          # Build files + package.json + node_modules (se necessário)
          zip -r release.zip . \
            -x "*.git*" \
            -x "src/*" \
            -x "public/*" \
            -x ".env*" \
            -x "*.md" \
            -x "tsconfig.json" \
            -x "vite.config.*" \
            -x "*.test.*" \
            -x "*.spec.*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_NAME_FRONTEND }}
          publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
          package: .

      - name: Verify deployment health
        run: |
          echo "Waiting for deployment to be ready..."
          APP_URL="https://${{ secrets.APP_NAME_FRONTEND }}.azurewebsites.net"

          for i in {1..12}; do
            echo "Health check attempt $i/12..."

            # Tentar acessar a URL do app
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL" || echo "000")

            if [ "$HTTP_CODE" == "200" ] || [ "$HTTP_CODE" == "304" ]; then
              echo "✅ App is healthy! (HTTP $HTTP_CODE)"
              echo "Deployment successful: $APP_URL"
              exit 0
            elif [ "$HTTP_CODE" != "000" ]; then
              echo "⚠️ App returned HTTP $HTTP_CODE"
            else
              echo "App not responding yet..."
            fi

            if [ $i -lt 12 ]; then
              echo "Waiting 15 seconds before next check..."
              sleep 15
            fi
          done

          echo "❌ App health check failed after 3 minutes"
          echo "Please check the deployment at: $APP_URL"
          exit 1